/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JLabel;

/**
 *
 * @author Flavio A. Pareja
 */
public class FirstMap extends javax.swing.JFrame {
     Random Rnd = new Random(); 
     int x;
     int y;
     int AleatorioX; 
     int AleatorioY; 
     Runnable a; 
     int h,k; 
      
    /**
     * Creates new form Arbolito
     */
    public FirstMap() throws InterruptedException {
      
        initComponents();
        h=0; k=0;
        this.PosicionAleatoria();
        this.y = Jugador.getY();
        this.x = Jugador.getX();
        
       // this.setUndecorated(true);
       this.addKeyListener(new KeyListener()
               {
               public void keyPressed(KeyEvent ke) {
               
                    switch(ke.getKeyCode()){
                        
                    case KeyEvent.VK_UP:{
                     if(AnalMovimiento(1,1,x,y))
                     Jugador.setLocation(x,y);
                     y = y-6;
                    break;
                                        
                    }
                    case KeyEvent.VK_LEFT:{
                    //J1.currentDirection=Bomberman.LEFT;
                   
                    if(AnalMovimiento(1,1,x,y))
                    Jugador.setLocation(x,y);
                     x = x-6;
                     
                    break;
                    }
                    case KeyEvent.VK_RIGHT:{
                    //J1.currentDirection=Bomberman.RIGHT;
                   
                    if(AnalMovimiento(1,1,x,y)){
                     Jugador.setLocation(x, y);
                     x = x+6;}
                    break;
                    }
                    case KeyEvent.VK_DOWN:{
                    //J1.currentDirection=Bomberman.DOWN;
                    
                     if(AnalMovimiento(1,1,x,y)){
                    Jugador.setLocation(x,y);
                     y = y+6;}
                    break;
                    }
                    
                }
                    
                   System.out.println("X:" + h + ", Y:" + k);
                   PosX.setText(String.valueOf(x)); 
                   PosY.setText(String.valueOf(y));
                   if ((Jugador.getX()+50>h && Jugador.getX()-50<h)) {
                       if (!(Jugador.getY()+50>k && Jugador.getY()-50<k)) {
                           Lucha L = new Lucha(); 
                           L.setVisible(true);
                       }
                       
                   }
                   
               }              

            @Override
            public void keyTyped(KeyEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyReleased(KeyEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

               });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Jugador = new javax.swing.JLabel();
        Pokemon = new javax.swing.JLabel();
        Map = new javax.swing.JLabel();
        Etiqueta_Pos_X = new javax.swing.JLabel();
        PosX = new javax.swing.JLabel();
        Etiqueta_Pos_Y = new javax.swing.JLabel();
        PosY = new javax.swing.JLabel();

        setLocation(new java.awt.Point(50, 50));
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("True"), this, org.jdesktop.beansbinding.BeanProperty.create("undecorated"));
        bindingGroup.addBinding(binding);

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(null);

        Jugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maps/Jugador.gif"))); // NOI18N
        Jugador.setText(".");
        getContentPane().add(Jugador);
        Jugador.setBounds(240, 490, 50, 90);

        Pokemon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/Primer.gif"))); // NOI18N
        Pokemon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PokemonMouseClicked(evt);
            }
        });
        getContentPane().add(Pokemon);
        Pokemon.setBounds(140, 170, 160, 150);

        Map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maps/FirstMap.png"))); // NOI18N
        getContentPane().add(Map);
        Map.setBounds(0, 0, 590, 600);

        Etiqueta_Pos_X.setText("Pos X: ");
        getContentPane().add(Etiqueta_Pos_X);
        Etiqueta_Pos_X.setBounds(600, 10, 50, 14);

        PosX.setText("0");
        getContentPane().add(PosX);
        PosX.setBounds(600, 30, 40, 14);

        Etiqueta_Pos_Y.setText("Pos Y: ");
        getContentPane().add(Etiqueta_Pos_Y);
        Etiqueta_Pos_Y.setBounds(600, 50, 50, 14);

        PosY.setText("0");
        getContentPane().add(PosY);
        PosY.setBounds(600, 70, 40, 14);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean AnalMovimiento(int Nivel, int zona, int x, int y){
        switch (Nivel){
          case 1:
              if (x==324 && ((y<552 && y>366) || (y<300 && y>228))) {
                  //(Y<552 && Y>366) && (Y<300 && Y>228) // BordeCasa
                  return false;                   
              }
              if (y==222 && (x>368 && x<530)) {
                  // 222 380 530 /7 Limite Superior Y CASA 
                  return false; 
              }
              if (x==512 && (y>48 && y<222)) {
                  return false; 
              }
              if (x==158 && ( y<600 && y>378) || (y==378 && (x>116 && x<158))) {
                  return false; 
              }
              if (y==42) {
                  return false; 
              }
              break;           
      }  
        
    return true;     
    }
    
    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
           
    }//GEN-LAST:event_formComponentResized

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
       
    }//GEN-LAST:event_formKeyReleased

    private void PokemonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PokemonMouseClicked

       // TODO add your handling code here:
       
    }//GEN-LAST:event_PokemonMouseClicked

    /**
     * @param args the command line arguments
     */
    public void PosicionAleatoria() throws InterruptedException{    
    this.AleatorioX = (int)(Rnd.nextDouble()*326); 
    this.AleatorioY = (int)(Rnd.nextDouble()*251);   
    SetPosicion(AleatorioX, AleatorioY);
    //EsperarSegundos();
    
    }
    public void EsperarSegundos() throws InterruptedException{
    int a = (int)(Rnd.nextDouble()* 90 + 45 );
    Thread.sleep(a*1000);
    }
    public void SetPosicion(int x, int y){
       
            this.h=AleatorioX; 
            this.k=AleatorioY; 
            this.Pokemon.setLocation(h,k);
            

   
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                   
                    new FirstMap().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(FirstMap.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Etiqueta_Pos_X;
    private javax.swing.JLabel Etiqueta_Pos_Y;
    private javax.swing.JLabel Jugador;
    private javax.swing.JLabel Map;
    private javax.swing.JLabel Pokemon;
    private javax.swing.JLabel PosX;
    private javax.swing.JLabel PosY;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
